services:
  - type: web
    name: TripNest
    runtime: docker
    branch: main
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromSecret: SUPABASE_DATABASE_URL
      - key: Cloudinary__CloudName
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: Cloudinary__ApiKey
        fromSecret: CLOUDINARY_API_KEY
      - key: Cloudinary__ApiSecret
        fromSecret: CLOUDINARY_API_SECRET
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: AllowedHosts
        value: "*"
    autoDeploy: true