services:
  - type: web
    name: TripNest
    runtime: docker        
    branch: main

    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromSecret: DATABASE_URL
      - key: Cloudinary__CloudName
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: Cloudinary__ApiKey
        fromSecret: CLOUDINARY_API_KEY
      - key: Cloudinary__ApiSecret
        fromSecret: CLOUDINARY_API_SECRET
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: Logging__LogLevel__Default
        value: Information
      - key: Logging__LogLevel__Microsoft_AspNetCore
        value: Warning
      - key: AllowedHosts
        value: "*"
    autoDeploy: true